freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  matrix:
    env:
      FLAG_NONE: true
    env:
      FLAG_SSL: --with-ssl
      FLAG_MEMPROF: --enable-memprof
      FLAG_DEBUG: --enable-debug
  install_script: pkg install -y pcre
  script:
    - ./configure --prefix="$PWD/fuzzpre" $FLAG_SSL $FLAG_MEMPROF $FLAG_DEBUG
    # Speed up CI builds
    - printf '/CFLAGS+=/s/-g//\ns/-O2//\nw\nq\n' | ed -s src/Makefile
    - make
    - make install
