freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  matrix:
    env:
      FLAG_NONE: true
    env:
      FLAG_SSL: --with-ssl
      FLAG_MEMPROF: --enable-memprof
      FLAG_DEBUG: --enable-debug
  install_script: pkg install -y pcre
  script:
    - ./configure --prefix="$PWD/fuzzpre" $FLAG_SSL $FLAG_MEMPROF $FLAG_DEBUG
    - make
    - make install
