#ifndef _EXTERNS_AUTO_H
#define _EXTERNS_AUTO_H

int add_muf_delay_event(int delay, int descr, dbref player, dbref loc, dbref trig, dbref prog, struct frame *fr, const char *mode);
int add_muf_delayq_event(int delay, int descr, dbref player, dbref loc, dbref trig, dbref prog, const char *argstr, const char *cmdstr, int listen_p);
int add_muf_timer_event(int descr, dbref player, dbref prog, struct frame *fr, int delay, char *id);
int add_muf_tread_event(int descr, dbref player, dbref prog, struct frame *fr, int delay);
int array_delitem(stk_array ** harr, array_iter * item);
int array_delrange(stk_array ** harr, array_iter * start, array_iter * end);
void clear_propnode(PropPtr p);
void copy_proplist(dbref obj, PropPtr * newer, PropPtr old);
void diskbase_debug(dbref player);
char * displayprop(dbref player, dbref obj, const char *name, char *buf, size_t bufsiz);
void do_abort_silent(void);
void do_edit(int descr, dbref player, const char *name);
void do_leave(int descr, dbref player);
void do_memory(dbref who);
void do_newpassword(dbref player, const char *name, const char *password);
void do_propset(int descr, dbref player, const char *name, const char *prop);
void do_score(dbref player);
void do_sweep(int descr, dbref player, const char *name);
void do_tune(dbref player, char *parmname, char *parmval, int full_command_has_delimiter);
int exit_loop_check(dbref source, dbref dest);
const char * exit_prefix(register const char *string, register const char *prefix);
int fetch_propvals(dbref obj, const char *dir);
dbref find_mlev(dbref prog, struct frame * fr, int st);
void flush_user_output(dbref player);
int format_time(char *buf, int max_len, const char *fmt, struct tm *tmval);
long get_tz_offset(void);
dbref getparent(dbref obj);
int gui_dlog_freeall_descr(int descr);
void gui_initialize(void);
void init_match_remote(int descr, dbref player, dbref what, const char *name, int type, struct match_data *md);
void list_proglines(dbref player, dbref program, struct frame *fr, int start, int end);
void listenqueue(int descr, dbref player, dbref where, dbref trigger, dbref what, dbref xclude, const char *propname, const char *toparg, int mlev, int mt, int mpi_p);
void log_status(char *format, ...);
int mcpframe_to_descr(McpFrame * ptr);
int mcpframe_to_user(McpFrame * ptr);
void muf_backtrace(dbref player, dbref program, int count, struct frame *fr);
int muf_debugger(int descr, dbref player, dbref program, const char *text, struct frame *fr);
void muf_dlog_purge(struct frame *fr);
void muf_event_add(struct frame *fr, char *event, struct inst *val, int exclusive);
int muf_event_count(struct frame* fr);
int notify_nolisten(dbref player, const char *msg, int isprivate);
int notify_from_echo(dbref from, dbref player, const char *msg, int isprivate);
int notify_from(dbref from, dbref player, const char *msg);
int ok_password(const char *password);
int ok_player_name(const char *name);
void prog_clean(struct frame *fr);
int prop_read_perms(dbref player, dbref obj, const char *name, int mlev);
int prop_write_perms(dbref player, dbref obj, const char *name, int mlev);
int pset_user(int c, dbref who);
void san_main(void);
void sane_dump_object(dbref player, const char *arg);
void sanechange(dbref player, const char *command);
void sanfix(dbref player);
void sanity(dbref player);
int scopedvar_poplevel(struct frame *fr);
void send_contents(int descr, dbref loc, dbref dest);
void set_signals(void);
void set_source(dbref player, dbref action, dbref source);
long size_boolexp(struct boolexp *b);
long size_prog(dbref prog);
long size_properties(dbref player, int load);
long size_proplist(PropPtr avl);
void spit_file_segment(dbref player, const char *filename, const char *seg);
void spit_file(dbref player, const char *filename);
char * strip_ansi(char *buf, const char *input);
char * strip_bad_ansi(char *buf, const char *input);
int test_lock(int descr, dbref player, dbref thing, const char *lockprop);
int test_lock_false_default(int descr, dbref player, dbref thing, const char *lockprop);
char * time_format_2(long dt);
void tune_save_parmsfile(void);
void tune_freeparms(void);
const char * unparse_flags(dbref thing);
void untouchprops_incremental(int limit);

#endif /* _EXTERNS_AUTO_H */
