   To enable SSL connections, run configure with the  --with-ssl=SSLTOP 
argument. SSLTOP should be /usr, /usr/local, or whatever path contains the
sub-paths 'lib/libssl.so' and 'include/ssl.h' or 'include/openssl/ssl.h'.

   This has been tested against:
OpenSSL 0.9.5a 1 Apr 2000 (Under Solaris 2.7)
OpenSSL 0.9.6a 5 Apr 2001 (Under Solaris 2.7)
OpenSSL 0.9.6a (Under Redhat Linux 7.2)

   Any other versions may not work, but you're free to try.

   Once you're done running configure, the muck will compile the same,
except a self-signed certificate will be created for you, and possibly
the random number generator will be seeded from /etc/passwd and /etc/hosts.

   You'll be prompted for your Muck name, your email address, and the DNS 
name of the muck. Be sure that the IP address of your muck reverse-lookups 
to the name you specify here! Clients will use this to confirm they've 
reached the right muck.

   You'll need to make sure your newly created certificate 'game/server.pem'
is in the muck 'game' directory when the muck is started; otherwise, it will
complain.

   If, for some reason, you are using a server.pem file that contains a
password encrypted private key, you can @tune ssl_keyfile_passwd to the
apropriate password.  This kludge will be addressed soon.

   To see the information in your certificate, do: 

openssl x509 -text < server.pem

   To create a secure socket, use the -sport option, rather than -port. You
can create multiple secure and nonsecure ports using these two command
line arguments. You will probably need to modify restart to do this.

   The default type of port to create is nonsecure (clear-text).

   [ Instructions to get a signed certificate and other stuff here ]
