/*
 * Copyright (c) 1991-2015 by Fuzzball Software
 * under the GNU Public License
 *
 * Some parts of this code Copyright (c) 1990 Chelsea Dyerman
 * University of California, Berkeley (XCF)
 */

/*
 * This file is generated by mkversion. Any changes made will go away.
 */

#include "config.h"

#include "externs.h"
#include "interface.h"

#define generation "$generation"
#define creation "$creation"
$gitavail

typedef struct hash_file_entry {
	const char *filename;
	const char *githash;
	const char *sha1hash;
} hash_file_entry;

static hash_file_entry hash_file_array[] = {
$hasharray
	{ NULL, NULL, NULL }
};

void
do_version(dbref player)
{
	notifyf(player, "Version: %s(%s) Compiled on: %s", VERSION, generation, creation);
	notifyf(player, "Options: %s", compile_options);
}

void
do_hashes(dbref player, char *args) {
	hash_file_entry *entry;
	int b_git = 0, b_sha1 = 0;
	const char *filename;

	if (!args || !*args)
	{
#ifdef GIT_AVAILABLE
		notify(player, "usage: @hashes [all|git|sha1]");
#else
		notify(player, "usage: @hashes [all|sha1]");
#endif
		notify(player, "Show hashes calculated for source files at compile time");
		notify(player, "");
		notify(player, "all   - Show all available hashes");
#ifdef GIT_AVAILABLE
		notify(player, "git   - Show only the git hash (if available)");
#endif
		notify(player, "sha1  - Show only the sha1 hash");
		return;
	}

	/* What hashes to display? */
	if (!strcasecmp(args, "git")) {
		b_git = 1;
	} else if (!strcasecmp(args, "sha1")) {
		b_sha1 = 1;
	} else {
		b_sha1 = 1;
#ifdef GIT_AVAILABLE
		b_git = 1;
#endif
	}

	/* Header */
	notify(player, "File            Hash");

	entry = hash_file_array;
	while (entry && entry->filename) {
		filename = entry->filename;

		if (b_sha1 && entry->sha1hash) {
			notifyf(player, "%-15s %s (sha1)", filename, entry->sha1hash);
			filename = "";
		}

		if (b_git && entry->githash) {
			notifyf(player, "%-15s %s (git)", filename, entry->githash);
		}

		entry++;
	}
}

